const MUSIC_DATA = [
    {
        id: 1,
        song: "Human",
        artist: "The Killers",
        category: "Alternative",
        album: "Day & Age",
        year: "2008",
        video:"https://www.youtube.com/watch?v=xeH9a0WG17o",
        cover: {
          imgSrc: '/albums/day&age.jpg',
          alt: "",
        },
      },
      {
        id: 2,
        song: "Little Freak",
        artist: "Harry Styles",
        category: "Pop",
        album: "Harry's House",
        year: "2022",
        video: "//www.youtube.com/watch?v=8gKLHrN1ozY",
        cover: {
          imgSrc: '/albums/Harry.jpg',
          alt: "",
        },
      },
      {
        id: 3,
        song: "Hold the Line",
        artist: "Toto",
        category: "Rock",
        album: "Toto",
        year: "1978",
        video: "https://www.youtube.com/watch?v=OVZmL9FJXE0",
        cover: {
          imgSrc: '/albums/toto.jpg',
          alt: "",
        },
      },
      {
        id: 4,
        song: "Dance The Night",
        artist: "Dua Lipa",
        category: "Pop",
        album: "Barbie",
        year: "2018",
        video:"https://www.youtube.com/watch?v=KQvYQPpkm4U",
        cover: {
          imgSrc: '/albums/dua.jpg',
          alt: "",
        },
      },
      {
        id: 5,
        song: "Imagination",
        artist: "Foster the People",
        category: "Alternative",
        album: "Imagination - Single",
        year: "2019",
        video:"https://www.youtube.com/watch?v=4C7EGz5EwYE",
        cover: {
          imgSrc: '/albums/foster.jpg',
          alt: "",
        },
      },
      {
        id: 6,
        song: "Sue Me",
        artist: "Sabrina Carpenter",
        category: "Pop",
        album: "Singular Act I",
        year: "2018",
        video: "https://www.youtube.com/watch?v=GMdgU7I8s7A",
        cover: {
          imgSrc: '/albums/sabrina.jpg',
          alt: "",
        },
      },
      {
        id: 7,
        song: "Bad Romance",
        artist: "Lady Gaga",
        category: "Pop",
        album: "The Fame Monster",
        year: "2009",
        video: "https://www.youtube.com/watch?v=TTOPBQhrvtQ",
        cover: {
          imgSrc: '/albums/lady.jpg',
          alt: "",
        },
      },
      {
        id: 8,
        song: "Life is a Highway",
        artist: "Rascal Flatts",
        category: "SoundTrack",
        album: "Cars SoundTrack",
        year: "2006",
        vide:"",
        cover: {
          imgSrc: '/albums/cars.jpg',
          alt: "",
        },
      },
      {
        id: 9,
        song: "21 Guns",
        artist: "Green Day",
        category: "Alternative",
        album: "21st Century Breakdown",
        year: "2009",
        video:"",
        cover: {
          imgSrc: '/albums/green.jpg',
          alt: "",
        },
      },
      {
        id: 10,
        song: "Bad Liar",
        artist: "Imagine Dragons",
        category: "Alternative",
        album: "Origins",
        year: "2018",
        video:"",
        cover: {
          imgSrc: '/albums/imagine.jpg',
          alt: "",
        },
      },
      {
        id: 11,
        song: "When You're Gone",
        artist: "Avril Lavigne",
        category: "Pop",
        album: "The Best Damn Thing",
        year: "2007",
        video:"",
        cover: {
          imgSrc: '/albums/avril.jpg',
          alt: "",
        },
      },
      {
        id: 12,
        song: "Paradise",
        artist: "Coldplay",
        category: "Alternative",
        album: "Mylo Xyloto",
        year: "2011",
        cover: {
          imgSrc: '/albums/cold.jpg',
          alt: "",
        },
      },
      {
        id: 13,
        song: "California Girls",
        artist: "Katy Perry",
        category: "Pop",
        album: "Teenage Dream",
        year: "2010",
        cover: {
          imgSrc: '/albums/katy.jpg',
          alt: "",
        },
      },
      {
        id: 14,
        song: "Get Him Back!",
        artist: "Olivia Rodrigo",
        category: "Pop",
        album: "GUTS",
        year: "2023",
        cover: {
          imgSrc: '/albums/olivia.jpg',
          alt: "",
        },
      },
      {
        id: 15,
        song: "Ride",
        artist: "Twenty One Pilots",
        category: "Alternative",
        album: "Blurryface",
        year: "2015",
        cover: {
          imgSrc: '/albums/twenty.jpg',
          alt: "",
        },
      },
      {
        id: 16,
        song: "Nina",
        artist: "Ed Sheeran",
        category: "Pop",
        album: "X",
        year: "2024",
        cover: {
          imgSrc: '/albums/ed.jpg',
          alt: "",
        },
      },
      {
        id: 17,
        song: "Don't Let Me Down",
        artist: "The Chainsmokers",
        category: "Dance",
        album: "Collage",
        year: "2016",
        cover: {
          imgSrc: '/albums/cha.jpg',
          alt: "",
        },
      },
      {
        id: 18,
        song: "Red",
        artist: "Taylor Swift",
        category: "Pop",
        album: "Red",
        year: "2021",
        cover: {
          imgSrc: '/albums/taylor.jpg',
          alt: "",
        },
      },
      {
        id: 19,
        song: "All at Once",
        artist: "The Fray",
        category: "Rock",
        album: "How to Save a Life",
        year: "2005",
        cover: {
          imgSrc: '/albums/walk.jpg',
          alt: "",
        },
      },
      {
        id: 20,
        song: "Somebody Else",
        artist: "The 1975",
        category: "Alternative",
        album: "I like it when you sleep,for you are so beautiful yet so unware of it",
        year: "2016",
        cover: {
          imgSrc: '/albums/the.jpg',
          alt: "",
        },
      },
];

export default MUSIC_DATA;